### ISSUE TITLE
Demo Location Crash

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#245]
When pressing on the geolocation button in the demo detail page or demo list page the app crashes because it cannot find `place_name` of undefined:

```
JS: mapbox result {
JS:   "type": "FeatureCollection",
JS:   "query": [
JS:     -86.6488697,
JS:     36.0456808
JS:   ],
JS:   "features": [
JS:     {
JS:       "id": "address.725018952766604",
JS:       "type": "Feature",
JS:       "place_type": [
JS:         "address"
JS:       ],
JS:       "relevance": 1,
JS:       "properties": {},
JS:       "text_en": "Crossings Boulevard",
JS:       "place_name_en": "5429 Crossings Boulevard, Antioch, Tennessee 37013, United States",
JS:       "text": "Crossings Boulevard",
JS:       "place_name": "5429 Crossings Boulevard, Antioch, Tennessee 37013, United States",
JS:       "center": [
JS:         -86.648648,
JS:         36.045779
JS:       ],
JS:       "geometry": {
JS:         "type": "Point",
JS:         "coordinates": [
JS:           -86.648648,
JS:           36.045779
JS:         ]
JS:       },
JS:       "address": "5429",
JS:       "context": [
JS:         {
JS:           "id": "postcode.9422116604478160",
JS:           "text_en": "37013",
JS:           "text": "37013"
JS:         },
JS:         {
JS:           "id": "place.8222277984984890",
JS:           "wikidata": "Q4774998",
JS:           "text_en": "Antioch",
JS:         ...
JS: passei no handler de angular
JS: sending
10-12 16:04:15.807 25719 25719 E AndroidRuntime:     at httpModule.getJSON.then.r (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/mobile/core/services/location.service.js:46:93)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-12 16:04:15.807 25719 25719 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: 
System.err: Error: Uncaught (in promise): TypeError: Cannot read property 'place_name' of undefined
System.err: TypeError: Cannot read property 'place_name' of undefined
System.err:     at httpModule.getJSON.then.r (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/mobile/core/services/location.service.js:46:93)
System.err:     at ZoneDelegate.invoke (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)
System.err:     at Object.onInvoke (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:3890:37)
System.err:     at ZoneDelegate.invoke (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:387:32)
System.err:     at Zone.run (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:43)
System.err:     at file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:34
System.err:     at ZoneDelegate.invokeTask (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:421:31)
System.err:     at Object.onInvokeTask (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:3881:37)
System.err:     at ZoneDelegate.invokeTask (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:420:36)
System.err:     at Zone.runTask (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:188:47)
System.err:     at drainMicroTaskQueue (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:595:35)
System.err: File: "file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 155, column: 24
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'resolvePromise', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 825, column: 31
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 888, column: 17
System.err: 	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 421, column: 31
System.err: 	Frame: function:'onInvokeTask', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 3881, column: 37
System.err: 	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 420, column: 36
System.err: 	Frame: function:'Zone.runTask', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 188, column: 47
System.err: 	Frame: function:'drainMicroTaskQueue', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 595, column: 35
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by bradmartin** [comment]
Switched out the `poi` for `address` in the features collection which should be more reliable for our current mapbox http request.
