### ISSUE TITLE
NativeScriptException: 

### ISSUE THREAD

**Issue by bradmartin** [PushTracker/EvalApp#299]
https://sentry.io/maxmobility/smarteval/issues/625613715/

```
NativeScriptException: 
Calling js method run failed

Error: Uncaught (in promise): TypeError: Cannot read property 'extend' of undefined
TypeError: Cannot read property 'extend' of undefined
    at new SnackBar (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-snackbar/snackbar.js:7:79)
    at new BluetoothService (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js:23:25)
    at _createClass (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8447:24)
    at _createProviderInstance (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8417:30)
    at resolveNgModuleDep (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8380:25)
    at NgModuleRef_.get (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9088:20)
    at resolveNgModuleDep (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8400:33)
    at NgModuleRef_.get (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9088:20)
    at resolveDep (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9453:49)
    at createClass (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9333:36)
    at createDirectiveInstance (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9210:24)
    at createViewNodes (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:10430:40)
    at createRootView (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:10344:9)
    at callWithDebugContext (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:11375:29)
    at Object.debugCreateRootView [as createRootView] (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:10862:16)
    at ComponentFactory_.create (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8690:33)
    at ComponentFactoryBoundToModule.create (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:3381:33)
    at ViewContainerRef_.createComponent (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8800:49)
    at DetachedLoader.loadWithFactory (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/common/detached-loader.js:38:34)
    at PageRouterOutlet.activateOnGoForward (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:270:45)
    at PageRouterOutlet.activateWith (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:248:14)
    at ActivateRoutes.activateRoutes (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4158:44)
    at file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4109:23
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4108:33)
    at ActivateRoutes.activateRoutes (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4165:26)
    at file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4109:23
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/router/bundles/router.umd.js:4108:33)
    at ActivateRoutes.activate (file:///data/data/com.permobil.smarteval/files/app/...
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
    at com.tns.Runtime.callJSMethod(Runtime.java:983)
    at com.tns.Runtime.callJSMethod(Runtime.java:967)
...
(9 additional frame(s) were not displayed)


Calling js method run failed

Error: Uncaught (in promise): TypeError: Cannot read property 'extend' of undefined
TypeError: Cannot read property 'extend' of undefined
    at new SnackBar (file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-snackbar/snackbar.js:7:79)
    at new BluetoothService (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js:23:25)
    at _createClass (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8447:24)
    at _createProviderInstance (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8417:30)
    at resolveNgModuleDep (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:8380:25)
    at NgModuleRef_.get (file:///data/data/com.permobil.smarteval/files/app/tns_modules/@angular/core/bundles/core.umd.js:9088:20)
    at resolveNgModul...
```

**Comment by bradmartin** [comment]
Update to Snackbar(4.0.0) should have fixed this.
