### ISSUE TITLE
uuid change and name change events fail

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#35]
here is an example error output from uuid change:

```

JS: uuid: [Landroid.os.Parcelable;@8daa448
JS: 9C:DF:03:0C:4A:78 - uuid change - 00001101-0000-1000-8000-00805f9b34fb
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
05-14 15:30:10.088 28463 28463 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.device.action.UUID flg=0x10 (has extras) } in com.nativescript.TNS_BroadcastReceiver@1bb9ba
System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
System.err: 	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
System.err: 	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onReceive failed
System.err:
System.err: TypeError: UUIDs.indexOf is not a function
System.err: File: "file:///data/data/com.maxmobility.eval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js, line: 476, column: 28
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'isPushTracker', file:'file:///data/data/com.maxmobility.eval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js', line: 476, column: 29
System.err: 	Frame: function:'onDeviceUuidChange', file:'file:///data/data/com.maxmobility.eval/files/app/tns_modules/@maxmobility/mobile/core/services/bluetooth.service.js', line: 210, column: 23
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/com.maxmobility.eval/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err: 	Frame: function:'BluetoothCommon.sendEvent', file:'file:///data/data/com.maxmobility.eval/files/app/tns_modules/nativescript-bluetooth/common.js', line: 78, column: 14
System.err: 	Frame: function:'TNS_BroadcastReceiver.onReceive', file:'file:///data/data/com.maxmobility.eval/files/app/tns_modules/nativescript-bluetooth/android/TNS_BroadcastReceiver.js', line: 46, column: 31
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.nativescript.TNS_BroadcastReceiver.onReceive(TNS_BroadcastReceiver.java:14)
System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
System.err: 	... 9 more
ActivityManager: Process com.maxmobility.eval (pid 28463) has died: fore TOP
ActivityManager: setHasOverlayUi called on unknown pid: 28463
```

**Comment by finger563** [comment]
scratch that - that's a failure in the `onDeviceUuidChange` code within `bluetooth.service.ts`

**Comment by finger563** [comment]
I see some device failures (and random disconnects of the PT from the phone) which i think are a driver level issue caused by differences in how they react to us failing to read the name / uuids properly.  it throws up a stack trace any time the name is changed and on most devices thats no issue, but i do see on some devices it causes them to lose connection (i think)

**Comment by finger563** [comment]
name works - UUID still always returns null
