### ISSUE TITLE
Add GIFs to the connectivity and related pages

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#55]

**Comment by bradmartin** [comment]
@finger563 @devondoebele - do we have the .gif files for this yet?

**Comment by bradmartin** [comment]
branch `issue-55` has the files and is in order to work but it's not rendering the .gifs on the 1 and 3 slide on pairing.component.

It is possible the .gif files we have are not supported by the native libs. I'll try them in a plain NS app to see if they work, if so that will rule out the plugin/native libraries and then it is possible that an older issue on the plugin about 'angular usage' is valid and I'll find a fix for it 👍 shouldn't be anything major.

**Comment by finger563** [comment]
on android they show but don't play (and on the plus side they are transparent :) )

**Comment by finger563** [comment]
i updated the code so that the `html` uses `<Gif></Gif>` instead of the `<Image></Image>` it was using - now I'm getting this console output (and associated crash):

```
JS: gif loaded
JS: Gif(166)
JS: ~/assets/images/gifs/PT-APP-CONNECT2.gif
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
System.err: 
System.err: Error: pl.droidsonroids.gif.GifIOException: GifError 0: No error
System.err:     pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
System.err:     pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:51)
System.err:     pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:125)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     android.app.Fragment.performCreateView(Fragment.java:2352)
System.err:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
System.err:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
System.err:     android.app.BackStackRecord.run(BackStackRecord.java:815)
System.err:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1582)
System.err:     android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
System.err:     android.os.Handler.handleCallback(Handler.java:751)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6776)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
System.err: File: "file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-gif/gif.js, line: 87, column: 33
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'Gif._setSrcProperty', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-gif/gif.js', line: 87, column: 34
System.err: 	Frame: function:'Gif.(anonymous function)', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-gif/gif.js', line: 66, column: 14
System.err: 	Frame: function:'applyAllNativeSetters', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 960, column: 28
System.err: 	Frame: function:'initNativeView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 904, column: 9
System.err: 	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 627, column: 22
System.err: 	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 272, column: 18
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 231, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'CarouselCommon.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-carousel/index-common.js', line: 28, column: 35
System.err: 	Frame: function:'Carousel.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/nativescript-carousel/index.js', line: 79, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 208, column: 35
System.err: 	Frame: function:'Page.onLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 43, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 434, column: 18
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 588, column: 24
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.permobil.smarteval/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err: 	at android.app.Fragment.performCreateView(Fragment.java:2352)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
System.err: 	at android.app.BackStackRecord.run(BackStackRecord.java:815)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1582)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
System.err: Caused by: pl.droidsonroids.gif.GifIOException: GifError 0: No error
System.err: 	at pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
System.err: 	at pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:51)
System.err: 	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:125)
System.err: 	... 20 more
JS: **** App Uncaught Error Event **** Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
ActivityManager: Process com.permobil.smarteval (pid 23210) has died(274,1171)
ActivityManager: cleanUpApplicationRecord -- 23210
```

**Comment by finger563** [comment]
figured it out - has to do with using `[src]="slide.Image"` instead of directly setting `src="~/assets/images/gifs/PT-APP-CONNECT2.gif"` - when using the direct approach then it doesn't crash the app and the gif plays :)

**Comment by finger563** [comment]
I've pushed a hack that allows us to see the gifs working on android (the 2  out of 3 gifs we have)

**Comment by finger563** [comment]
On iOS there are no errors, but the gifs don't actually show

**Comment by finger563** [comment]
Aaaaand I just saw that your changes we're on branch `issue-55` : facepalm:

**Comment by bradmartin** [comment]
You got suckered by the ole branch switheroo 😜 (never fun time).

I wanted to narrow down the issue we are facing, so below are what I have so far:

The gifs work fine in a plain NS app (tested in the plugin repo's demo) for both android and iOS.

So the plugin might need a fix for the Angular side of things, but it looks like the native lib the plugin uses is not an issue or the .gif files we have 👍 so that's good.

**Comment by bradmartin** [comment]
![screenshot_1531537113](https://user-images.githubusercontent.com/6006148/42720176-f0cbc7be-86e7-11e8-9fe9-5927a26bbbe5.png)
