### ISSUE TITLE
Webpack for Production

### ISSUE THREAD

**Issue by bradmartin** [PushTracker/EvalApp#9]
Before moving to production with releases, making sure the app is webpacked correctly is important for faster boot times with angular apps.

**Comment by bradmartin** [comment]
No that we're on NS5x and running latest bits, I'm hopeful the bundling with webpack is simpler to wrap around our app.

I'll look at this to see if the `--bundle` command works. If not, it'll take some extra work, plus lots of testing to ensure nothing is broken during the webpack bundling. So we will likely do this for `v1.1`

**Comment by finger563** [comment]
So since you moved this to 1.1 does that mean that the `--bundle` flag didn't work?

**Comment by bradmartin** [comment]
I was thinking more like, it's likely not going to 😅 - and if it did, we'd probably need very very thorough testing with the clinical ed team and others, many different scenarios and every thing tested.

Not sure if a week is enough, we'd likely want to use the bundled version for EVERY release so we can see if things get broken due to any webpack config issues during bundling.

I wouldn't feel comfortable shipping in a week or so with only one `--bundle` release, if that makes sense.

**Comment by bradmartin** [comment]
Currently bundle is:

```

WARNING in ../node_modules/nativescript-sqlite/sqlite.js
Module not found: Error: Can't resolve 'nativescript-sqlite-commercial' in '/Users/bradmartin/projects/EvalApp/maxmobility/apps/eval-mobile/node_modules/nativescript-sqlite'
 @ ../node_modules/nativescript-sqlite/sqlite.js
 @ ../node_modules/kinvey-nativescript-sdk/kinvey-nativescript-sdk.js
 @ ./app.component.ts
 @ ./app.module.ts
 @ ./main.ts

WARNING in ../node_modules/nativescript-sqlite/sqlite.js
Module not found: Error: Can't resolve 'nativescript-sqlite-encrypted' in '/Users/bradmartin/projects/EvalApp/maxmobility/apps/eval-mobile/node_modules/nativescript-sqlite'
 @ ../node_modules/nativescript-sqlite/sqlite.js
 @ ../node_modules/kinvey-nativescript-sdk/kinvey-nativescript-sdk.js
 @ ./app.component.ts
 @ ./app.module.ts
 @ ./main.ts

ERROR in /Users/bradmartin/projects/EvalApp/maxmobility/nativescript-bluetooth/bluetooth.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Users/bradmartin/projects/EvalApp/maxmobility/nativescript-bluetooth/bluetooth.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/bradmartin/projects/EvalApp/maxmobility/apps/eval-mobile/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:740:23)
    at plugin.done.then (/Users/bradmartin/projects/EvalApp/maxmobility/apps/eval-mobile/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ /Users/bradmartin/projects/EvalApp/maxmobility/xplat/mobile/core/services/bluetooth.service.ts 5:0-79 20:30-39 63:27-36 64:27-36 65:27-36 66:27-36 67:27-36 68:27-36 69:27-36 75:27-36 76:27-36 77:27-36 78:27-36 79:27-36 83:28-37 84:28-37 85:28-37 86:28-37 87:28-37 88:28-37 89:28-37 90:28-37 91:28-37 92:28-37 93:28-37 94:28-37 287:17-26 292:17-26 303:17-26 375:17-32 399:17-32
 @ /Users/bradmartin/projects/EvalApp/maxmobility/xplat/mobile/core/services/index.ts
 @ /Users/bradmartin/projects/EvalApp/maxmobility/xplat/mobile/core/index.ts
 @ /Users/bradmartin/projects/EvalApp/maxmobility/xplat/mobile/index.ts
 @ ./app.module.ts
 @ ./main.ts
Webpack compilation complete. Watching for file changes.
Webpack build done!
```

So need to fix a few things for it to be somewhat workable.

**Comment by bradmartin** [comment]
This is definitely an improvement in error output from the last webpack attempts a month or so ago, so it's gone in a positive direction at the least.

**Comment by bradmartin** [comment]
Closed via https://github.com/PushTracker/EvalApp/pull/371
